export class Trabalhador {
    constructor(
        public iCodigo: number = null,
        public iTipo: number = null,
        public sNome: string = null,
        public iSexo: number = null,
        public iEstadoCivil: number = null,
        public iRacaCor: number = null,
        public sCPF: string = null,
        public sNisPisPasep: string = null,
        public iGrauInstrucao: number = null,
        public iPrimeiroEmprego: number = null,
        public sCodiNomeTravTrans: string = null,
        public dtDataNasc: string = null,
        public iCodMunicipioNasc: number = null,
        public sUfNasc: string = null,
        public iPaisNasc: number = null,
        public iNacionalidade: number = null,
        public sNomeMae: string = null,
        public sNomePai: string = null,
        public sNumCTPS: string = null,
        public sNumSerieCTPS: string = null,
        public sUfCTPS: string = null,
        public sNumRG: string = null,
        public sEmissaoRG: string = null,
        public dtExpedRG: string = null,
        public sNumRegOC: string = null,
        public sEmissaoOC: string = null,
        public dtExpedOC: string = null,
        public dtValidadeOC: string = null,
        public sNumCNH: string = null,
        public dtExpedCNH: string = null,
        public sUfCNH: string = null,
        public dtValidadeCNH: string = null,
        public iCatCNH: number = null,
        public dtPrimeiraHab: string = null,
        public sTipoLogradouro: string = null,
        public sLogradouro: string = null,
        public sNumero: string = null,
        public sComplemento: string = null,
        public sBairro: string = null,
        public sCEP: string = null,
        public iCodMunicipioRes: number = null,
        public sUfRes: string = null,
        public sDefFisica: string = null,
        public sDefVisual: string = null,
        public sDefAuditiva: string = null,
        public sDefMental: string = null,
        public sDefIntelectual: string = null,
        public sRecebeBeneficioPrev: string = null,
        public sTelefone1: string = null,
        public sTelefone2: string = null,
        public sEmail: string = null,
        public sEmail2: string = null,
        public sDescricao: string = null,
        public iVerificado: number = null,
        public dtCadastro: string = null,
        public dtUltimaAtualizacao: string = null

    ) {
        
    }
}