export class TrabalhadorConsulta {
    constructor(
        public iCodigo: string = null,
        public sVinculo: string = null,
        public sNome: string = null,
        public sSexo: string = null,
        public sEstadoCivil: string = null,
        public sRacaCor: string = null,
        public sCPF: string = null,
        public sNisPisPasep: string = null,
        public sGrauInstrucao: string = null,
        public sPrimeiroEmprego: string = null,
        public sNomeTravTrans: string = null,
        public dtDataNasc: string = null,
        public sMunicipioNasc: string = null,
        public sUfNasc: string = null,
        public sPaisNasc: string = null,
        public sNacionalidade: string = null,
        public sNomeMae: string = null,
        public sNomePai: string = null,
        public sNumCTPS: string = null,
        public sNumSerieCTPS: string = null,
        public sUfCTPS: string = null,
        public sNumRG: string = null,
        public sEmissaoRG: string = null,
        public dtExpedRG: string = null,
        public sNumRegOC: string = null,
        public sEmissaoOC: string = null,
        public dtExpedOC: string = null,
        public dtValidadeOC: string = null,
        public sNumCNH: string = null,
        public dtExpedCNH: string = null,
        public sUfCNH: string = null,
        public dtValidadeCNH: string = null,
        public sCatCNH: string = null,
        public dtPrimeiraHab: string = null,
        public sTipoLogradouro: string = null,
        public sLogradouro: string = null,
        public sNumero: string = null,
        public sComplemento: string = null,
        public sBairro: string = null,
        public sCEP: string = null,
        public sMunicipioRes: string = null,
        public sUfRes: string = null,
        public sDefFisica: string = null,
        public sDefVisual: string = null,
        public sDefAuditiva: string = null,
        public sDefMental: string = null,
        public sDefIntelectual: string = null,
        public sRecebeBeneficioPrev: string = null,
        public sTelefone1: string = null,
        public sTelefone2: string = null,
        public sEmail: string = null,
        public sEmail2: string = null
    ) {
        
    }
}